spring.application.name=son
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url= jdbc:postgresql://192.168.15.109:5432/sonProject_v1
spring.datasource.username=postgres
spring.datasource.password=postgres

server.address=0.0.0.0
server.port=8888

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect